来源：http://yanruoqin.com/js-async/004.html#%E9%97%AE%E9%A2%98
promise主要胜在链式调用和错误处理。
# 1 回调地狱
回调嵌套回调
回调的坏处：
1 多层嵌套，不易维护
2 错误处理，每层嵌套都需要对于成功失败分别做处理
try catch只能捕获到同步错误，异步回调中的错误捕获不到


# 2 promise 链式调用，避免嵌套
面试官眼中的promise:https://juejin.im/post/5c233a8ee51d450d5a01b712
1 回调函数延迟绑定（通过then传入）
2 返回值穿透（返回也是promise）
```bash
Promise.resolve('foo').then(Promise.resolve('bar')).then(function (result) {
  console.log(result); //foo
});
相当于
Promise.resolve('foo').then(null).then(function (result) {
  console.log(result);
});
```
3 错误冒泡
```bash
readFilePromise('1.json').then(data => {
    return readFilePromise('2.json');
}).then(data => {
    return readFilePromise('3.json');
}).then(data => {
    return readFilePromise('4.json');
}).catch(err => {
  // xxx
})
这样前面产生的错误会一直向后传递，被 catch 接收到，就不用频繁地检查错误了。
```
对于promise中未能捕获的错误，可以通过监听window的unhandledrejection来捕获

## 2.1 promise构造是同步的，里面的resolve和reject是异步的，这两个是作为微任务放到事件循环中的
## 2.2 怎么实现一个promise
https://www.taopoppy.cn/node/three_asyncDepth_promise1.html#_4-promise-catch
只要记住：then就是为promise添加状态改变时的回调函数就行
```bash
1 内部状态流转
2 then 方法
改变状态，回调赋值
最终then的结果都是返回一个新创建的promise对象
3 reject和resolve
function Promise(fun){
  this.status = 'pending'
  this.fill =null
  this.reject = null
  function resolve(val){
    if(this.status != pending) return
    this.fill(val)
    this.status = 'resolve'
  }
  function rejectfun(err){
    if(this.status != pending) return
    this.reject(err)
    this.status = 'reject'
  }
  fun(resolve,rejectfun)
}
Promise.prototype.then = function(full,reject){
  if(this.status = 'pending'){
    this.full = full
    this.reject = reject
  }else if (this.status === FULFILLED) {
    //如果状态是fulfilled,则执行成功回调，并将成功值传入
    onFulfilled(this.value);
  } else {
    //如果状态是rejected，直接执行失败回调，并将失败原因传入
    onRejected(this.error);
  }
  return 新的promise
}
```
then方法再好好看看，链式是怎么实现的，then里面不是函数或者是一个返回promise的函数是怎么处理的
```bash
Promise.resolve('foo').then(Promise.resolve('bar')).then(function (result) {
  console.log(result); //foo
});
相当于
Promise.resolve('foo').then(null).then(function (result) {
  console.log(result);
});
//
Promise.resolve('foo').then((res)=>{return Promise.resolve('bar')}).then(function (result) {
  console.log(result); //bar
});
//
let p1 = new Promise((resolve,reject)=> {
  // 第一层具体执行逻辑
  resolve(1)           // Promise(1)
}).then(res=>{
  // 第二层具体执行逻辑
  return 2             // Promise(2)
}).then(res =>{
  // 第三层具体执行逻辑
  console.log(res)            // Promise(3)  //2
}).then(res=>{console.log(res)}).catch(err=>{
  console.log(err)
})
只要有一个抛出错误，后面的then就不会执行
```

catch与then中穿进去的reject是相同的其实
 整个Promise链中，catch只属于异步触发它当中回调函数执行的那个Promise，并不属于所有Promise

#5. Promise.all
## 2.3  promise 的缺点
创建即执行，不能取消
无法获知执行状态
## 2.4 错误捕获
无论是then还是catch中注册的回调函数，都是由promise的状态变动触发的
Promise的构造函数，以及被then调用执行的函数是在try...catch 代码块中执行的，所以在这些代码中即使使用throw ，程序本身也不会因为异常而终止。
### 2.4.1使用reject而不是throw
//
```bash
var p1 = new Promise(function(resolve, reject) {
  setTimeout(() => {
      throw Error('async error')   //这里换成reject就能捕获到
  }) //这里的错误就无法捕获到，因为第一轮事件循环的时候执行then的时候并没有触发更新状态（then中是microtask）
})
.then(res => {
  console.log(res)
  console.log('程序正常执行了')
})
.catch(err => {
  console.log(err)
  console.log('捕获到错误了')
})
```
1 catch函数在同一个时间点只属于某一个Promise，因为它的主人是随着程序的执行而不断变化的
2 catch在最早报错的时候就catch了，后续的promise就不执行了
Promise.all 和 Promise.race ,因为这个两个方法处理多个异步调用的时候是并行的，而在Async函数当中是无法并行处理的，所以即便在当前Async-Await风靡的时候，依旧不得不用Promise这两个方法来提高效率。
### 2.4.2 关于then传入的resolve函数的返回值
Promise会将最后的值存储起来，如果在下次使用promise方法的时候回直接返回该值的promise

## 2.5 promise.all不是一个个的顺序执行的，而是同时开始、并行执行的
如果所有的Promise中只有一个执行错误，那么整个Promise.all不会走Promise.all().then()这个流程了，而是走Promise.all().catch()这个流程，但是要注意的是虽然走到了Promise.all().catch()这个流程，但是不影响其他Promise的正常执行
# 3 generator和协程
生成器是es6的语法
生成器语法
```bash
function * gen(){
  a = yeild funtion(){}
  b = yeild funtion(){}
}
g = gen()
g.next()
1 调用 gen() 后，程序会阻塞住，不会执行任何语句。
2 调用 g.next() 后，程序继续执行，直到遇到 yield 程序暂停。
3 next 方法返回一个对象， 有两个属性: value 和 done。value 为当前 yield 后面的结果，done 表示是否执行完，遇到了return 后，done 会由false变为true。
```
## 3.1 生成器是如何让程序停止和恢复的
1 协程：
协程是一种比线程更加轻量级的存在，协程处在线程的环境中，一个线程可以存在多个协程，可以将协程理解为线程中的一个个任务。不像进程和线程，协程并不受操作系统的管理，而是被具体的应用程序代码所控制。
2 协程的运作
一个线程一次只能执行一个协程。比如当前执行 A 协程，另外还有一个 B 协程，如果想要执行 B 的任务，就必须在 A 协程中将JS 线程的控制权转交给 B协程，那么现在 B 执行，A 就相当于处于暂停的状态。
3 如何让generator的异步函数顺序执行
```bash
const readFileThunk = (filename) => {
  return (callback) => {
    fs.readFile(filename, callback);
  }
}
const gen = function* () {
  const data1 = yield readFileThunk('001.txt')
  console.log(data1.toString())
  const data2 = yield readFileThunk('002.txt')
  console.log(data2.toString)
}
let g = gen();
// 第一步: 由于进场是暂停的，我们调用next，让它开始执行。
// next返回值中有一个value值，这个value是yield后面的结果，放在这里也就是是thunk函数生成的定制化函数，里面需要传一个回调函数作为参数
g.next().value((err, data1) => {
  // 第二步: 拿到上一次得到的结果，调用next, 将结果作为参数传入，程序继续执行。
  // 同理，value传入回调
  g.next(data1).value((err, data2) => {
    g.next(data2);
  })
})
```
也可以通过promise来实现
最终是利用co这个库
# 4 async 和await   
es7中新增的(2016年)
async/await被称为 JS 中异步终极解决方案
async/await利用协程和Promise实现了同步方式编写异步代码的效果
async 是一个通过异步执行并隐式返回 Promise 作为结果的函数
await 对后面返回的promise执行then
## 4.1 定义
async函数是定义会返回promise的函数的简便写法,只是一个简单的函数，只不过是会对结果进行封装
```bash
function f() {
    return Promise.resolve('TEST');
}

// asyncF is equivalent to f!
async function asyncF() {
    return 'TEST';
}
function f() {
    return Promise.reject('Error');
}
// asyncF is equivalent to f!
async function asyncF() {
    throw 'Error';
}
```
## 4.2 async返回值
1 返回promise是正常情况
2 返回一个普通值，会被promise包装，且promise状态为fullfilled，resovle的值为该普通值
3 没有返回，会被promise包装，且promise状态为fullfilled，resovle的值为undefined
如果在async函数外使用promise，我们依然需要使用then和回调函数
```bash
async function f1 () {
    return 10;
}
console.log(f1());     // Promise {<resolved>: 10}
fn1().then(function (x) {
  console.log(x);      // 10
})
```
## 4.3 await本质（只不过是语法糖，会创建一个promise且把后面的代码放在then中）
每次我们使用await，解释器会创建一个promise然后把async函数中的后续代码（也就是书写在await后面的代码）放到then回调里，并被计划在promise完成之后执行。 
```bash
// await写法
await foo();         
console.log("hello");

// .then写法
foo().then(() => {
    console.log("hello");
});
```
## 4.4 async和await的错误优雅处理
```bash
    const [err, data] = await fetchData().then(data => [null, data] ).catch(err => [err, null])
````
# 4.1 foreach中async不能顺序执行，但是for of 却可以
因为for  of是用迭代器去遍历的（生成器本身就是一个迭代器）


